Fix compilation errors in MonoDevelop
The errors only show on MonoDevelop (works fine when compiling from
Unity) The errors are caused because we are passing an array as
parameter to List<> methods.

Errors fixed:

IntegrationTestsRunnerWindow.cs(233,26): Error CS0123: A method or delegate `Extensions.Contains(this int[], int)' parameters do not match delegate `System.Predicate<UnityTest.TestComponent>(UnityTest.TestComponent)' parameters (CS0123) (Assembly-CSharp-Editor-vs)

IntegrationTestsRunnerWindow.cs(233,26): Error CS1502: The best overloaded method match for `System.Collections.Generic.List<UnityTest.TestComponent>.RemoveAll(System.Predicate<UnityTest.TestComponent>)' has some invalid arguments (CS1502) (Assembly-CSharp-Editor-vs)

IntegrationTestsRunnerWindow.cs(233,26): Error CS1503: Argument `#1' cannot convert `method group' expression to type `System.Predicate<UnityTest.TestComponent>' (CS1503) (Assembly-CSharp-Editor-vs)